# Generated by Django 5.0.4 on 2024-04-20 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Доступные удобства', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Желаемая вселенная', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Желаемая местность', max_length=50)),
                ('description', models.CharField(help_text='Описание', max_length=500)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Entertaiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название отеля', max_length=50)),
                ('description', models.CharField(help_text='Описание', max_length=500)),
                ('cost', models.PositiveSmallIntegerField(help_text='Цена за ночь', null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.area')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название отеля', max_length=50)),
                ('description', models.CharField(help_text='Описание', max_length=500)),
                ('cost_per_night', models.PositiveSmallIntegerField(help_text='Цена за ночь')),
                ('commodity', models.ManyToManyField(help_text='Выберите доступные удобства', to='touring.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор тура', primary_key=True, serialize=False)),
                ('checkin_date', models.DateField(help_text='Дата заселения')),
                ('checkout_date', models.DateField(help_text='Дата выезда')),
                ('cost', models.PositiveSmallIntegerField(help_text='Итоговая стоимость')),
                ('entertaiments', models.ForeignKey(help_text='Заказанные развлечения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.entertaiment')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.hotel')),
            ],
        ),
    ]
