# Generated by Django 5.0.4 on 2024-04-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='touring.area'),
        ),
    ]
