# Generated by Django 5.0.4 on 2024-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertaiment',
            name='cost',
            field=models.PositiveSmallIntegerField(help_text='Цена', null=True),
        ),
    ]
