# Generated by Django 5.0.4 on 2024-04-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0002_remove_tour_entertaiments_tour_entertaiments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='area',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='touring.area'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='entertaiments',
            field=models.ManyToManyField(help_text='Заказанные развлечения', to='touring.entertaiment'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='touring.hotel'),
        ),
    ]
