# Generated by Django 5.0.4 on 2024-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0002_hotel_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='description',
            field=models.CharField(help_text='Описание вселенной', max_length=500, null=True),
        ),
    ]
