# Generated by Django 5.0.4 on 2024-04-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0003_tour_area_alter_tour_entertaiments_alter_tour_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touring.area'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touring.hotel'),
        ),
    ]
