# Generated by Django 5.0.4 on 2024-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0004_alter_tour_area_alter_tour_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
