# Generated by Django 5.0.4 on 2024-04-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0004_remove_tour_entertaiments_tour_entertaiments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='cost',
        ),
    ]
