# Generated by Django 5.0.4 on 2024-04-20 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0005_alter_tour_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='entertaiments',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='area',
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.hotel'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор тура', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Entertaiment',
        ),
    ]
