# Generated by Django 5.0.4 on 2024-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0005_remove_tour_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='entertaiments',
        ),
        migrations.AddField(
            model_name='tour',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Итоговая стоимость', null=True),
        ),
    ]
