# Generated by Django 5.0.4 on 2024-04-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0006_remove_tour_entertaiments_tour_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='entertaiments',
            field=models.ManyToManyField(help_text='Заказанные развлечения', to='touring.entertaiment'),
        ),
    ]
