# Generated by Django 5.0.4 on 2024-04-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0003_direction_description'),
        ('touring', '0006_remove_tour_entertaiments_remove_tour_area_and_more'),
    ]

    operations = [
    ]
