# Generated by Django 5.0.4 on 2024-05-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0007_tour_entertaiments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'permissions': (('can_view', 'Set all tours'),)},
        ),
    ]
