# Generated by Django 5.0.4 on 2024-05-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='entertaiments',
        ),
        migrations.AddField(
            model_name='tour',
            name='entertaiments',
            field=models.ForeignKey(help_text='Заказанные развлечения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.entertaiment'),
        ),
    ]
