# Generated by Django 5.0.4 on 2024-05-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0010_remove_tour_cost_remove_tour_entertaiments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='touring.area'),
        ),
    ]
