# Generated by Django 5.0.4 on 2024-05-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0011_tour_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Итоговая стоимость', null=True),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='entertaiments',
        ),
        migrations.AddField(
            model_name='tour',
            name='entertaiments',
            field=models.ManyToManyField(help_text='Заказанные развлечения', to='touring.entertaiment'),
        ),
    ]
