# Generated by Django 5.0.4 on 2024-05-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0012_tour_cost_remove_tour_entertaiments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='cost',
        ),
    ]
