# Generated by Django 5.0.4 on 2024-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touring', '0013_remove_tour_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users_photos'),
        ),
    ]
